### ISSUE TITLE
Assets path

### ISSUE THREAD

**Issue by AvaelKross** [trenpixster/addict#71]
And again it's me who is not familiar with Phoenix :)

I'm wondering why addict's generator puts css/js files right in priv/static/{css,js} ? As far as I can see, this folder is mentioned in .gitignore for many projects. Say if I'm cooperating with my friend via git, only one of us will have assets files by default. It doesn't seem to be a correct behavior, but maybe I'm wrong about something.

**Comment by trenpixster** [comment]
Hey @AvaelKross! Are you referring to [this](https://github.com/phoenixframework/phoenix/blob/e3c23a364af4f2283e2498fdb47c60161f262a1f/installer/templates/static/brunch/.gitignore#L13) type of use case? I usually create projects without `brunch`. Where would you propose to have those files instead? Maybe hardcoding the assets into the base view is the way to go in order to be completely independent from the Front End requirements of each project.

Keep 'em coming 😄
